package com.travelman.business.service.billing;

import java.util.*;

public class AlphaNumericAutoGenerator
{
   
    public static String[] autoGenerated(int n,int length)
    {
        String[] str=new String[n];
        String str1="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        StringBuilder sb=new StringBuilder(length);
        Random r = new Random();

    
        for(int i=0;i<n;i++)
        {
            for(int j=0;j<length;j++)
            {
                sb.append(str1.charAt(r.nextInt(str1.length())));
            }
           str[i]=sb.toString();
          
            sb.delete(0,length);
        }
        return  str;
    }
}

